### ISSUE TITLE
infografia_PedroGarcia

### ISSUE THREAD

**Issue by PedroGarcia15** [SistemasTecTlaxiaco/actividad-1-infografia-PedroGarcia15#2]
![1](https://github.com/user-attachments/assets/1955acc9-bca1-49b1-849f-1dedbf11f4fe)
![2](https://github.com/user-attachments/assets/5cc30412-f936-4987-959b-f3873b31ce1c)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica tiene un 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
